//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGateLogistics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbOpenGateEntities : DbContext
    {
        public dbOpenGateEntities()
            : base("name=dbOpenGateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoriaproveedor> categoriaproveedor { get; set; }
        public virtual DbSet<estadofactura> estadofactura { get; set; }
        public virtual DbSet<estadoproveedor> estadoproveedor { get; set; }
        public virtual DbSet<nacionalidadproveedor> nacionalidadproveedor { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<factura> factura { get; set; }
    
        public virtual ObjectResult<SP_BUSQUEDA_PROVEEDORES_Result> SP_BUSQUEDA_PROVEEDORES(string proveedores)
        {
            var proveedoresParameter = proveedores != null ?
                new ObjectParameter("Proveedores", proveedores) :
                new ObjectParameter("Proveedores", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSQUEDA_PROVEEDORES_Result>("SP_BUSQUEDA_PROVEEDORES", proveedoresParameter);
        }
    
        public virtual ObjectResult<sp_proveedor_datosgrafica_Result> sp_proveedor_datosgrafica()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_proveedor_datosgrafica_Result>("sp_proveedor_datosgrafica");
        }
    }
}
