//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGateLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int id { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public int CategoriaProveedor_Id { get; set; }
        public int NacionalidadProveedor_Id { get; set; }
        public int EstadoProveedor_Id { get; set; }
    
        public virtual categoriaproveedor categoriaproveedor { get; set; }
        public virtual estadoproveedor estadoproveedor { get; set; }
        public virtual nacionalidadproveedor nacionalidadproveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
